services:
  hadolint:
    image: hadolint/hadolint:v1.13.0-debian@sha256:de7fda8f56488de4b3eff4809cb63a1053cce67670783d53292f52493c39897c
  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    volumes:
      - .:/home/node/src
  shellcheck:
    image: koalaman/shellcheck-alpine:v0.4.7
    volumes:
      - .:/mnt
  yamllint:
    command: ["--strict", ".yamllint", "."]
    image: boiyaa/yamllint:1.8.1
    volumes:
      - .:/workdir
version: '3'
