build-steps: &build-steps
  - checkout
  - setup_remote_docker
  - run:
      command: |
        ./bin/build.sh ${IMAGE_NAME} ${TAG}
        ./bin/test.sh ${IMAGE_NAME} ${TAG}
        mkdir -p ${IMAGE_PATH}
        docker save ${IMAGE_NAME}:${TAG} > ${IMAGE_PATH}/${IMAGE_NAME}_${TAG}.tar
      name: Build and test ${TAG} Docker image
  - persist_to_workspace:
      root: ${IMAGE_PATH}
      paths:
        - "*.tar"

job-defaults: &job-defaults
  docker:
    - image: docker:17.09.1-ce-git
  environment:
    IMAGE_NAME: keimlink/sphinx-doc
    IMAGE_PATH: docker-images

jobs:
  build-latest:
    <<: *job-defaults
    environment:
      TAG: latest
    steps:
      - *build-steps
  build-latex:
    <<: *job-defaults
    environment:
      TAG: latex
    steps:
      - *build-steps
  push:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ${IMAGE_PATH}
      - run:
          command: |
            docker login --username ${DOCKER_LOGIN} --password ${DOCKER_PASSWORD}
            docker load < ${IMAGE_PATH}/${IMAGE_NAME}_latest.tar
            ./bin/push.sh ${IMAGE_NAME} latest
            docker load < ${IMAGE_PATH}/${IMAGE_NAME}_latex.tar
            ./bin/push.sh ${IMAGE_NAME} latex
          name: Push Docker images to registry
  shellcheck:
    docker:
      - image: koalaman/shellcheck-alpine:v0.4.7
    steps:
      - checkout
      - run:
          command: find . -name "*.sh" -exec shellcheck {} +
          name: Check all shell scripts
  yamllint:
    docker:
      - image: boiyaa/yamllint:1.8.1
    steps:
      - checkout
      - run:
          command: yamllint --strict .yamllint .
          name: Check all YAML files

version: 2

workflows:
  build-push:
    jobs:
      - build-latest:
          requires:
            - shellcheck
            - yamllint
      - build-latex:
          requires:
            - shellcheck
            - yamllint
      - shellcheck
      - yamllint
      - push:
          filters:
            branches:
              only: master
          requires:
            - build-latest
            - build-latex
  version: 2
