jobs:
  build-alpine:
    docker:
      - image: docker:17.09.1-git
    steps:
      - run:
          command: |
            make build-alpine
            make smoke-test-alpine
          name: Build and test Alpine Docker image
  build-debian:
    docker:
      - image: docker:17.09.1-git
    steps:
      - run:
          command: |
            make build-debian
            make smoke-test-debian
          name: Build and test Debian Docker image
  push:
    docker:
      - image: docker:17.03.0-ce
    steps:
      - setup_remote_docker:
          version: 17.03.0-ce-git
      - run:
          command: |
            docker login --username $DOCKER_LOGIN --password $DOCKER_PASSWORD
          name: Push Docker images to registry
  shellcheck:
    docker:
      - image: koalaman/shellcheck-alpine:v0.4.7
    steps:
      - checkout
      - run:
          command: find . -name "*.sh" -exec shellcheck {} +
          name: Check all shell scripts
  yamllint:
    docker:
      - image: boiyaa/yamllint:1.8.1
    steps:
      - checkout
      - run:
          command: yamllint --strict .
          name: Check all YAML files

version: 2

workflows:
  build-push:
    jobs:
      - build-alpine:
          requires:
            - shellcheck
            - yamllint
      - build-debian:
          requires:
            - shellcheck
            - yamllint
      - shellcheck
      - yamllint
      - push:
          filters:
            branches:
              only: master
          requires:
            - build-alpine
            - build-debian
  version: 2
