jobs:
  build-alpine:
    docker:
      - image: docker:17.09.1-git
    steps:
      - checkout
      - run:
          command: |
            make build-alpine
            make smoke-test-alpine
          name: Build and test Alpine Docker image
  build-debian:
    docker:
      - image: docker:17.09.1-git
    steps:
      - checkout
      - run:
          command: |
            make build-debian
            make smoke-test-debian
          name: Build and test Debian Docker image
  push:
    docker:
      - image: docker:17.03.0-ce
    steps:
      - setup_remote_docker:
          version: 17.03.0-ce-git
      - run:
          command: |
            docker login --username $DOCKER_LOGIN --password $DOCKER_PASSWORD
          name: Push Docker images to registry

version: 2

workflows:
  build-push:
    jobs:
      - build-alpine:
      - build-debian:
      - push:
          filters:
            branches:
              only: master
          requires:
            - build-alpine
            - build-debian
  version: 2
