aliases:
  attach-workspace: &attach-workspace
    attach_workspace:
      at: ~/project
  docker-buildpack-deps: &docker-buildpack-deps
    docker:
      - image: circleci/buildpack-deps:stretch
  docker-node: &docker-node
    docker:
      - image: circleci/node:8
  persist-docker-images: &persist-docker-images
    persist_to_workspace:
      root: .
      paths: docker-images

jobs:
  analyze-pull-request:
    <<: *docker-node
    steps:
      - checkout
      - *attach-workspace
      - run:
          command: |
            if [ -n "${CIRCLE_PULL_REQUEST}" ]; then
              yarn danger ci
            else
              echo "Skipping Pull Request analysis." \
                "Please create a Pull Request to merge your changes."
              exit 1
            fi
          name: Analyze Pull Request
  yarn-install:
    <<: *docker-node
    steps:
      - checkout
      - *attach-workspace
      - restore_cache:
          keys:
            - v1-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-yarn-{{ .Branch }}-
            - v1-yarn-
          name: Restore Yarn cache
      - run:
          command: yarn ci
          name: Install dependencies
      - save_cache:
          key: v1-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
          name: Save Yarn cache
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: .
          paths: node_modules
  build-latest:
    <<: *docker-buildpack-deps
    environment:
      IMAGE_NAME: keimlink/sphinx-doc
    steps:
      - checkout
      - *attach-workspace
      - setup_remote_docker
      - run:
          command: |
            make build-latest smoke-test-latest
            mkdir -p docker-images
            ./bin/image.sh save ${IMAGE_NAME} latest > docker-images/sphinx-doc_latest.tar
          name: Build and test latest Docker image
      - *persist-docker-images
  build-latex:
    <<: *docker-buildpack-deps
    environment:
      IMAGE_NAME: keimlink/sphinx-doc
    steps:
      - checkout
      - *attach-workspace
      - setup_remote_docker
      - run:
          command: |
            make build-latex smoke-test-latex
            mkdir -p docker-images
            ./bin/image.sh save ${IMAGE_NAME} latex > docker-images/sphinx-doc_latex.tar
          name: Build and test latex Docker image
      - *persist-docker-images
  push:
    <<: *docker-buildpack-deps
    environment:
      IMAGE_NAME: keimlink/sphinx-doc
    steps:
      - setup_remote_docker
      - checkout
      - *attach-workspace
      - run:
          command: |
            docker login --username ${DOCKER_LOGIN} --password ${DOCKER_PASSWORD}
            docker load < docker-images/sphinx-doc_latest.tar
            ./bin/image.sh push ${IMAGE_NAME} latest
            docker load < docker-images/sphinx-doc_latex.tar
            ./bin/image.sh push ${IMAGE_NAME} latex
          name: Push Docker images to registry
  shellcheck:
    docker:
      - image: koalaman/shellcheck-alpine:v0.4.7
    environment:
      SHELL: /bin/sh -e -o pipefail
    steps:
      - checkout
      - run:
          command: apk update && apk add make
          name: Install GNU make
      - run:
          command: make shellcheck SHELLCHECK=shellcheck
          name: Check all shell scripts
  yamllint:
    docker:
      - image: boiyaa/yamllint:1.8.1
    steps:
      - checkout
      - run:
          command: yamllint --strict .yamllint .
          name: Check all YAML files
  yarn-check:
    <<: *docker-node
    steps:
      - checkout
      - *attach-workspace
      - run:
          command: yarn check
          name: Check yarn.lock
  yarn-lint:
    <<: *docker-node
    steps:
      - checkout
      - *attach-workspace
      - run:
          command: yarn lint
          name: Run all yarn lint checks

version: 2

workflows:
  build-push:
    jobs:
      - analyze-pull-request:
          context: org-global
          filters:
            branches:
              ignore:
                - develop
                - master
          requires:
            - yarn-check
      - build-latest:
          requires:
            - shellcheck
            - yamllint
            - yarn-lint
      - build-latex:
          requires:
            - shellcheck
            - yamllint
            - yarn-lint
      - yarn-install
      - shellcheck
      - yamllint
      - push:
          context: org-global
          filters:
            branches:
              only: master
          requires:
            - build-latest
            - build-latex
      - yarn-check:
          requires:
            - yarn-install
      - yarn-lint:
          requires:
            - yarn-check
  version: 2
