jobs:
  build-latest:
    docker:
      - image: docker:17.09.1-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            ./bin/build.sh keimlink/sphinx-doc latest
            ./bin/test.sh keimlink/sphinx-doc latest
            mkdir -p docker-images
            docker save keimlink/sphinx-doc:latest > docker-images/sphinx-doc_latest.tar
          name: Build and test latest Docker image
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - docker-images/*
  build-latex:
    docker:
      - image: docker:17.09.1-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            ./bin/build.sh keimlink/sphinx-doc latex
            ./bin/test.sh keimlink/sphinx-doc latex
            mkdir -p docker-images
            docker save keimlink/sphinx-doc:latex > docker-images/sphinx-doc_latex.tar
          name: Build and test latex Docker image
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - docker-images/*
  push:
    docker:
      - image: docker:17.09.1-ce-git
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run:
          command: |
            docker login --username ${DOCKER_LOGIN} --password ${DOCKER_PASSWORD}
            docker load < /tmp/workspace/sphinx-doc_latest.tar
            ./bin/push.sh keimlink/sphinx-doc latest
            docker load < /tmp/workspace/sphinx-doc_latex.tar
            ./bin/push.sh keimlink/sphinx-doc latex
          name: Push Docker images to registry
  shellcheck:
    docker:
      - image: koalaman/shellcheck-alpine:v0.4.7
    steps:
      - checkout
      - run:
          command: find . -name "*.sh" -exec shellcheck {} +
          name: Check all shell scripts
  yamllint:
    docker:
      - image: boiyaa/yamllint:1.8.1
    steps:
      - checkout
      - run:
          command: yamllint --strict .yamllint .
          name: Check all YAML files

version: 2

workflows:
  build-push:
    jobs:
      - build-latest:
          requires:
            - shellcheck
            - yamllint
      - build-latex:
          requires:
            - shellcheck
            - yamllint
      - shellcheck
      - yamllint
      - push:
          filters:
            branches:
              only: master
          requires:
            - build-latest
            - build-latex
  version: 2
